pipeline {
    agent any
    environment {
        PLAYWRIGHT_BROWSERS_PATH = 'C:\\Users\\CRISTIAN\\AppData\\Local\\ms-playwright'
    }
    stages {
        stage('Instalar dependencias') {
            steps {
                bat 'npm install'
                bat 'npx playwright install --with-deps'
            }
        }
        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }
        stage('Pruebas') {
            steps {
                bat 'npx playwright test --reporter=html'
            }
        }
    }
    post {
        always {
            publishHTML(target: [
                reportName: 'Playwright Report',
                reportDir: 'playwright-report',
                reportFiles: 'index.html'
            ])
        }
    }
}